// Copyright 2026 The Lattice Authors, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package service

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"time"

	"github.com/alatticeio/lattice/api/v1alpha1"
	"github.com/alatticeio/lattice/internal/agent/log"
	"github.com/alatticeio/lattice/internal/agent/store"
	"github.com/alatticeio/lattice/internal/server/models"
	"github.com/golang-jwt/jwt/v5"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	k8sclient "sigs.k8s.io/controller-runtime/pkg/client"
)

// ── Public types ──────────────────────────────────────────────────────────────

// EnrollmentTokenRequest is the input for CreateEnrollmentToken.
type EnrollmentTokenRequest struct {
	AllowedNamespace string
	AllowedTools     []string
	TTL              time.Duration // default 1 hour if zero
	CreatedBy        string
}

// EnrollmentTokenResponse is returned after creating an enrollment token.
type EnrollmentTokenResponse struct {
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expiresAt"`
}

// AgentRegisterRequest is sent by an Agent during initial registration.
type AgentRegisterRequest struct {
	// EnrollmentToken is the one-time token obtained from an admin.
	EnrollmentToken string
	// AgentName is the desired AgentIdentity / LatticePeer name.
	AgentName string
	// PublicKey is the WireGuard public key generated by the Agent.
	PublicKey string
	// Sandbox is the sandbox isolation mode for this agent.
	// Defaults to none.
	Sandbox v1alpha1.SandboxMode
}

// AgentRegisterResponse is returned after successful registration.
type AgentRegisterResponse struct {
	// JWT is the signed Agent JWT for all subsequent API calls.
	JWT string `json:"jwt"`
	// AgentIdentityName is the name of the created AgentIdentity CRD.
	AgentIdentityName string `json:"agentIdentityName"`
	// EnforcerMode is the user's preferred enforcer mode (iptables/ebpf) from their profile.
	EnforcerMode string `json:"enforcerMode,omitempty"`
}

// DelegateRequest is the input for creating a sub-agent enrollment token.
type DelegateRequest struct {
	// ParentJWT is the parent agent's signed JWT.
	ParentJWT string
	// AgentName is the desired name for the sub-agent.
	AgentName string
	// RequestedTools is the tool whitelist for the sub-agent.
	// Must be a subset of the parent's AllowedTools (when RoleName is empty).
	RequestedTools []string
	// RoleName, if non-empty, uses the parent's SpawnableRoles path.
	RoleName string
}

// DelegateResponse is the result of a successful DelegateToken call.
type DelegateResponse struct {
	// EnrollmentToken is a short-lived one-time token for the sub-agent to register.
	EnrollmentToken string    `json:"enrollmentToken"`
	ExpiresAt       time.Time `json:"expiresAt"`
}

// AgentRegistrationService manages Agent lifecycle: enrollment tokens,
// registration (WireGuard peer + AgentIdentity creation + JWT issuance),
// and revocation.
type AgentRegistrationService interface {
	CreateEnrollmentToken(ctx context.Context, req EnrollmentTokenRequest) (*EnrollmentTokenResponse, error)
	RegisterAgent(ctx context.Context, req AgentRegisterRequest) (*AgentRegisterResponse, error)
	RevokeAgent(ctx context.Context, namespace, agentName string) error
	ValidateAgentJWT(tokenStr string) (*models.AgentClaims, error)
	DelegateToken(ctx context.Context, req DelegateRequest) (*DelegateResponse, error)
}

// ── Implementation ────────────────────────────────────────────────────────────

type agentRegistrationService struct {
	logger    *log.Logger
	jwtSecret string
	store     store.Store
	k8s       k8sclient.Client
}

// NewAgentRegistrationService returns a new AgentRegistrationService.
// k8s may be nil in tests that don't exercise registration (token creation only).
func NewAgentRegistrationService(
	jwtSecret string,
	st store.Store,
	k8s k8sclient.Client,
) AgentRegistrationService {
	return &agentRegistrationService{
		logger:    log.GetLogger("agent-registration"),
		jwtSecret: jwtSecret,
		store:     st,
		k8s:       k8s,
	}
}

func (s *agentRegistrationService) CreateEnrollmentToken(ctx context.Context, req EnrollmentTokenRequest) (*EnrollmentTokenResponse, error) {
	ttl := req.TTL
	if ttl <= 0 {
		ttl = time.Hour
	}

	raw := make([]byte, 32)
	if _, err := rand.Read(raw); err != nil {
		return nil, fmt.Errorf("generate token: %w", err)
	}
	token := hex.EncodeToString(raw)

	toolsJSON, _ := json.Marshal(req.AllowedTools)
	expiresAt := time.Now().Add(ttl)

	tok := &models.AgentEnrollmentToken{
		Token:            token,
		AllowedNamespace: req.AllowedNamespace,
		AllowedTools:     string(toolsJSON),
		ExpiresAt:        expiresAt,
		CreatedBy:        req.CreatedBy,
	}
	if err := s.store.AgentEnrollmentTokens().Create(ctx, tok); err != nil {
		return nil, fmt.Errorf("store enrollment token: %w", err)
	}

	s.logger.Info("enrollment token created", "namespace", req.AllowedNamespace, "created_by", req.CreatedBy)
	return &EnrollmentTokenResponse{Token: token, ExpiresAt: expiresAt}, nil
}

func (s *agentRegistrationService) RegisterAgent(ctx context.Context, req AgentRegisterRequest) (*AgentRegisterResponse, error) {
	// 1. Validate enrollment token
	tok, err := s.store.AgentEnrollmentTokens().GetByToken(ctx, req.EnrollmentToken)
	if err != nil {
		s.logger.Warn("enrollment token lookup failed", "err", err)
		return nil, fmt.Errorf("invalid enrollment token")
	}
	if tok.UsedAt != nil {
		return nil, fmt.Errorf("enrollment token already used")
	}
	if time.Now().After(tok.ExpiresAt) {
		return nil, fmt.Errorf("enrollment token expired")
	}

	// 2. Parse allowed tools from token
	var allowedTools []string
	_ = json.Unmarshal([]byte(tok.AllowedTools), &allowedTools)

	// 3. Create LatticePeer (Agent registers its own public key)
	// Auto-join the peer to the first available network in the namespace so the
	// controller can allocate a VPN IP. Without a network association the peer
	// stays un-addressed and the sandbox binary can never start.
	var networkRef *string
	networkList := &v1alpha1.LatticeNetworkList{}
	if listErr := s.k8s.List(ctx, networkList, k8sclient.InNamespace(tok.AllowedNamespace)); listErr == nil && len(networkList.Items) > 0 {
		name := networkList.Items[0].Name
		networkRef = &name
	}

	peer := &v1alpha1.LatticePeer{
		ObjectMeta: metav1.ObjectMeta{
			Name:      req.AgentName,
			Namespace: tok.AllowedNamespace,
			Labels: map[string]string{
				"agent.lattice.io/managed": "true",
			},
		},
		Spec: v1alpha1.LatticePeerSpec{
			AppId:     req.AgentName,
			PublicKey: req.PublicKey,
			Network:   networkRef,
		},
	}
	if err = s.k8s.Create(ctx, peer); err != nil {
		return nil, fmt.Errorf("create LatticePeer: %w", err)
	}

	// 4. Create AgentIdentity
	sandboxMode := req.Sandbox
	if sandboxMode == "" {
		sandboxMode = v1alpha1.SandboxNone
	}
	identitySpec := v1alpha1.AgentIdentitySpec{
		PeerRef:           req.AgentName,
		AllowedTools:      allowedTools,
		AllowedNamespaces: []string{tok.AllowedNamespace},
		Sandbox:           sandboxMode,
		AuditLevel:        v1alpha1.AuditLevelWrite,
		EnforcementMode:   v1alpha1.EnforcementEnforce,
	}
	if tok.ParentAgentID != "" {
		identitySpec.ParentRef = tok.ParentAgentID
	}
	identity := &v1alpha1.AgentIdentity{
		ObjectMeta: metav1.ObjectMeta{
			Name:      req.AgentName,
			Namespace: tok.AllowedNamespace,
		},
		Spec: identitySpec,
	}
	if err = s.k8s.Create(ctx, identity); err != nil {
		// Rollback peer
		_ = s.k8s.Delete(ctx, peer)
		return nil, fmt.Errorf("create AgentIdentity: %w", err)
	}

	// 5. Mark token as used (single-use)
	if err = s.store.AgentEnrollmentTokens().MarkUsed(ctx, req.EnrollmentToken, time.Now()); err != nil {
		s.logger.Warn("failed to mark enrollment token used", "err", err)
	}

	// 6. Issue Agent JWT
	agentJWT, err := s.issueAgentJWT(req.AgentName, tok.AllowedNamespace, allowedTools, tok.ParentAgentID)
	if err != nil {
		return nil, fmt.Errorf("issue JWT: %w", err)
	}

	// 7. Look up user's enforcer_mode preference from their profile.
	var userEnforcerMode string
	workspace, wsErr := s.store.Workspaces().GetByNamespace(ctx, tok.AllowedNamespace)
	if wsErr == nil && workspace.CreatedBy != "" {
		profile, profErr := s.store.Profiles().Get(ctx, workspace.CreatedBy)
		if profErr == nil && profile.EnforcerMode != "" {
			userEnforcerMode = profile.EnforcerMode
		}
	}

	s.logger.Info("agent registered", "name", req.AgentName, "namespace", tok.AllowedNamespace)
	return &AgentRegisterResponse{
		JWT:               agentJWT,
		AgentIdentityName: req.AgentName,
		EnforcerMode:      userEnforcerMode,
	}, nil
}

func (s *agentRegistrationService) RevokeAgent(ctx context.Context, namespace, agentName string) error {
	identity := &v1alpha1.AgentIdentity{}
	identity.Name = agentName
	identity.Namespace = namespace
	if err := s.k8s.Get(ctx, k8sclient.ObjectKey{Namespace: namespace, Name: agentName}, identity); err != nil {
		return k8sclient.IgnoreNotFound(err)
	}
	if identity.Status.Phase == v1alpha1.AgentPhaseRevoked {
		return nil
	}
	patch := k8sclient.MergeFrom(identity.DeepCopy())
	identity.Status.Phase = v1alpha1.AgentPhaseRevoked
	if err := s.k8s.Status().Patch(ctx, identity, patch); err != nil {
		return fmt.Errorf("patch AgentIdentity status: %w", err)
	}
	s.logger.Info("agent revoked", "name", agentName, "namespace", namespace)
	return nil
}

func (s *agentRegistrationService) ValidateAgentJWT(tokenStr string) (*models.AgentClaims, error) {
	claims := &models.AgentClaims{}
	token, err := jwt.ParseWithClaims(tokenStr, claims, func(t *jwt.Token) (interface{}, error) {
		if _, ok := t.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, fmt.Errorf("unexpected signing method: %v", t.Header["alg"])
		}
		return []byte(s.jwtSecret), nil
	})
	if err != nil {
		return nil, err
	}
	if !token.Valid {
		return nil, fmt.Errorf("invalid agent JWT")
	}
	return claims, nil
}

func (s *agentRegistrationService) issueAgentJWT(agentName, namespace string, allowedTools []string, parentAgentID string) (string, error) {
	now := time.Now()
	claims := &models.AgentClaims{
		RegisteredClaims: jwt.RegisteredClaims{
			Subject:   agentName,
			IssuedAt:  jwt.NewNumericDate(now),
			ExpiresAt: jwt.NewNumericDate(now.Add(365 * 24 * time.Hour)),
			Issuer:    "lattice-agent-registration",
		},
		AgentID:       agentName,
		Namespace:     namespace,
		AllowedTools:  allowedTools,
		ParentAgentID: parentAgentID,
	}
	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	return token.SignedString([]byte(s.jwtSecret))
}

func (s *agentRegistrationService) DelegateToken(ctx context.Context, req DelegateRequest) (*DelegateResponse, error) {
	// 1. 验证父 Agent JWT
	parentClaims, err := s.ValidateAgentJWT(req.ParentJWT)
	if err != nil {
		return nil, fmt.Errorf("invalid parent JWT: %w", err)
	}

	var allowedTools []string

	if req.RoleName != "" {
		// SpawnableRoles 路径：子权限由管理员预授权的角色模板决定
		if s.k8s == nil {
			return nil, fmt.Errorf("k8s client required for SpawnableRoles")
		}
		parentIdentity := &v1alpha1.AgentIdentity{}
		if err = s.k8s.Get(ctx, k8sclient.ObjectKey{
			Namespace: parentClaims.Namespace,
			Name:      parentClaims.AgentID,
		}, parentIdentity); err != nil {
			return nil, fmt.Errorf("lookup parent AgentIdentity: %w", err)
		}
		found := false
		for _, r := range parentIdentity.Spec.SpawnableRoles {
			if r == req.RoleName {
				found = true
				break
			}
		}
		if !found {
			return nil, fmt.Errorf("role %q not in parent's spawnableRoles", req.RoleName)
		}
		roleIdentity := &v1alpha1.AgentIdentity{}
		if err = s.k8s.Get(ctx, k8sclient.ObjectKey{
			Namespace: parentClaims.Namespace,
			Name:      req.RoleName,
		}, roleIdentity); err != nil {
			return nil, fmt.Errorf("lookup role template %q: %w", req.RoleName, err)
		}
		allowedTools = roleIdentity.Spec.AllowedTools
	} else {
		// 派生路径：子权限 ⊆ 父权限
		parentToolSet := make(map[string]bool, len(parentClaims.AllowedTools))
		for _, t := range parentClaims.AllowedTools {
			parentToolSet[t] = true
		}
		for _, t := range req.RequestedTools {
			if !parentToolSet[t] {
				return nil, fmt.Errorf("tool %q not permitted by parent", t)
			}
		}
		allowedTools = req.RequestedTools
	}

	// 2. 生成一次性 enrollment token（TTL=15min），携带 parentAgentID
	raw := make([]byte, 32)
	if _, err = rand.Read(raw); err != nil {
		return nil, fmt.Errorf("generate token: %w", err)
	}
	token := hex.EncodeToString(raw)

	toolsJSON, _ := json.Marshal(allowedTools)
	expiresAt := time.Now().Add(15 * time.Minute)

	tok := &models.AgentEnrollmentToken{
		Token:            token,
		AllowedNamespace: parentClaims.Namespace,
		AllowedTools:     string(toolsJSON),
		ExpiresAt:        expiresAt,
		CreatedBy:        parentClaims.AgentID,
		ParentAgentID:    parentClaims.AgentID,
	}
	if err = s.store.AgentEnrollmentTokens().Create(ctx, tok); err != nil {
		return nil, fmt.Errorf("store delegate token: %w", err)
	}

	s.logger.Info("delegate token created", "parent", parentClaims.AgentID, "child", req.AgentName)
	return &DelegateResponse{EnrollmentToken: token, ExpiresAt: expiresAt}, nil
}
