apiVersion: v2
name: lattice
description: A self-hosted WireGuard mesh orchestration platform
type: application
version: 0.1.0
appVersion: "0.1.0"
icon: https://alattice.io/icon.png
home: https://alattice.io
sources:
  - https://github.com/alatticeio/lattice
keywords:
  - wireguard
  - vpn
  - mesh
  - overlay-network
  - kubernetes
maintainers:
  - name: Lattice Authors
    email: maintainers@alatticeio.io
    url: https://github.com/alatticeio/lattice
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Homepage
      url: https://alattice.io
    - name: GitHub
      url: https://github.com/alatticeio/lattice
