// Copyright 2026 The Lattice Authors, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package infra

import (
	"context"
	"encoding/binary"
	"fmt"
	"net"
	"net/netip"

	"golang.zx2c4.com/wireguard/conn"
	"golang.zx2c4.com/wireguard/wgctrl/wgtypes"
)

// Relay protocol constants.
const (
	RelayForward uint8 = 0x02 // Data forwarding
)

type RelayChannel interface {
	ReceiveFunc() conn.ReceiveFunc
	Send(ctx context.Context, remoteId uint64, relayType uint8, data []byte) error
	Connect() error
	// Connected reports whether a relay session is currently up, so callers can
	// decide whether relaying a signaling packet is worth trying.
	Connected() bool
	RemoteAddr() net.Addr
	Close() error
}

var (
	_ conn.Endpoint = (*RelayEndpoint)(nil)
)

func IDFromPublicKey(pubKey string) ([32]byte, error) {
	key, err := wgtypes.ParseKey(pubKey)
	if err != nil {
		return [32]byte{}, err
	}
	return key, nil
}

// relayFakePrefix is the fixed /96 ULA prefix used to encode Relay remote IDs
// as fake IPv6 addresses for display in wg show.
//
// "fd6c:7270:0000::" — "fd" (ULA) + "lr"(6c72) + "p"(7000).
// The lower 8 bytes carry the 64-bit RemoteId in big-endian order.
var relayFakePrefix = [8]byte{0xfd, 0x6c, 0x72, 0x70, 0x00, 0x00, 0x00, 0x00}

const RelayFakePort = 51820

// RelayFakeAddrPort encodes a Relay RemoteId as a fake IPv6 AddrPort.
// The resulting address looks like fd6c:7270:0000:0:<hi>:<hi>:<lo>:<lo>
// and is safe to pass to wg show / UAPI because it parses as a valid IP:port.
func RelayFakeAddrPort(remoteId uint64) netip.AddrPort {
	var b [16]byte
	copy(b[:8], relayFakePrefix[:])
	binary.BigEndian.PutUint64(b[8:], remoteId)
	return netip.AddrPortFrom(netip.AddrFrom16(b), RelayFakePort)
}

// IsRelayFakeAddr reports whether addr was generated by RelayFakeAddrPort.
func IsRelayFakeAddr(addr netip.Addr) bool {
	if !addr.Is6() {
		return false
	}
	b := addr.As16()
	return b[0] == relayFakePrefix[0] &&
		b[1] == relayFakePrefix[1] &&
		b[2] == relayFakePrefix[2] &&
		b[3] == relayFakePrefix[3] &&
		b[4] == relayFakePrefix[4] &&
		b[5] == relayFakePrefix[5]
}

// RemoteIdFromRelayFakeAddr extracts the RemoteId encoded in a fake Relay address.
func RemoteIdFromRelayFakeAddr(addr netip.Addr) uint64 {
	b := addr.As16()
	return binary.BigEndian.Uint64(b[8:])
}

// 1. Define a minimal custom Endpoint
type RelayEndpoint struct {
	// Physical layer info (for standard UDP/ICE)
	Addr netip.AddrPort

	// Protocol layer info (for Relay)
	RemoteId uint64

	// Flag: which path to use currently
	TransportType TransportType
}

func (e *RelayEndpoint) ClearSrc() {

}

func (e *RelayEndpoint) Clear() {}
func (e *RelayEndpoint) DstToString() string {
	// For display purposes (wg show / UAPI GET), always prefer the physical
	// relay address when available.  Routing is driven by DstToBytes() (which
	// uses RemoteId for Relay) and Send() (which checks TransportType), so
	// returning the relay IP:port here does not affect the data plane.
	if e.Addr.IsValid() {
		return e.Addr.String()
	}
	// Fallback: should not normally be reached because ReceiveFunc always sets
	// Addr to RelayFakeAddrPort(RemoteId).
	return fmt.Sprintf("relay://%d", e.RemoteId)
}

func (e *RelayEndpoint) DstToBytes() []byte {
	if e.TransportType == Relay {
		b := make([]byte, 8)
		binary.BigEndian.PutUint64(b, e.RemoteId)
		return b
	}
	// In standard UDP mode, convert AddrPort to bytes
	b, _ := e.Addr.MarshalBinary()
	return b
}

func (e *RelayEndpoint) DstIP() netip.Addr {
	if e.TransportType == Relay {
		// Relay routing is entirely determined by RemoteId, does not use UDP path,
		// return loopback for WireGuard internal rate limiting.
		return netip.IPv4Unspecified()
	}
	return e.Addr.Addr()
}

func (e *RelayEndpoint) SrcIP() netip.Addr {
	return netip.Addr{}
}
func (e *RelayEndpoint) SrcToString() string { return "" }
