apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lattice.fullname" . }}-config
  labels:
    {{- include "lattice.labels" . | nindent 4 }}
data:
  lattice.yaml: |
    app:
      listen: {{ .Values.config.app.listen }}
      name: "{{ .Values.config.app.name }}"
      env: "{{ .Values.config.app.env }}"
      {{- if .Values.config.demo.enabled }}
      demo:
        enabled: true
        ttl_minutes: {{ .Values.config.demo.ttlMinutes }}
        rate_limit_per_hour: {{ .Values.config.demo.rateLimitPerHour }}
      {{- end }}
    {{- if .Values.license.enabled }}
    license:
      file: /etc/lattice/license.jwt
    {{- end }}
    jwt:
      secret: {{ required "jwt.secret is required" (.Values.config.jwt.secret | default "") }}
      expire_hours: {{ .Values.config.jwt.expireHours }}
    {{- if not .Values.config.signalingUrl }}
    signaling-url: "nats://localhost:4222"
    {{- else }}
    signaling-url: "{{ .Values.config.signalingUrl }}"
    {{- end }}
    {{- if .Values.config.stunUrl }}
    stun-url: "{{ .Values.config.stunUrl }}"
    {{- end }}
    {{- if .Values.config.enforcerMode }}
    enforcer-mode: "{{ .Values.config.enforcerMode }}"
    {{- end }}
    {{- if .Values.config.database.dsn }}
    database:
      dsn: "{{ .Values.config.database.dsn }}"
    {{- end }}
